services:
  backend:
    build: ./pc_market_backend
    image: ghcr.io/sarkushev/jango_2/backend:latest   # эту строку пока оставьте, если хотите
    ports:
      - "8000:8000"
    volumes:
      - ./pc_market_backend:/app
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    # image: ghcr.io/sarkushev/jango_2/frontend:latest   # закомментируйте или удалите
    ports:
      - "80:80"
    depends_on:
      - backend